name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'src/*'
      - 'packages/**'
      - 'package.json'
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          fetch-depth: 0
      - name: setup git config
        run: |
          # setup the username and email.
          git config --global user.name "Catalyst Squad Automation"
          git config --global user.email "<opensource@catalystsquad.com>"
      - name: Get semver-tags
        run: |
          wget -c https://github.com/catalystsquad/semver-tags/releases/download/v0.3.3/semver-tags.tar.gz -O - | tar -xz
      - name: Semver Tags Dry Run
        id: semver-tags
        run: |
          ./.github/scripts/dorelease.sh fullrun
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: "${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: "${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}"
      - name: Install dependencies
        run: npm ci
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTOMATION_NPM_TOKEN }}
        run: |
          echo "Building and Publishing packages"
          npm run build:packages
          npm run build
          for i in ${{ steps.semver-tags.outputs.NEEDS_NPM }}
          do
            echo "Publishing $i"
            cd $i
            npm publish
            cd -
          done
